apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: up9pfnu2f-java-springboot 
  janus-idp.io/tekton: up9pfnu2f-java-springboot
  backstage.io/kubernetes-id: up9pfnu2f-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up9pfnu2f-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml